# Generated by Django 3.2.6 on 2021-08-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_company_companydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='CompanyInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.companyinfo'),
        ),
    ]
