# Generated by Django 3.2.6 on 2021-08-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_companydata_companyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='CompanyInfo',
            new_name='Trade_name',
        ),
    ]
