# Generated by Django 3.2.6 on 2021-08-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_companyinfo_companydata_trade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='Trade_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='companyInfo',
        ),
    ]
