# Generated by Django 3.2.6 on 2021-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210810_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='volume',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
