# Generated by Django 3.2.6 on 2021-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_companydata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
