# Generated by Django 3.2.6 on 2021-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_companydata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='open',
            field=models.FloatField(null=True),
        ),
    ]
