# Generated by Django 3.2.6 on 2021-08-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20210810_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
